---
- name: Destroy AWS Intances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/ctjon

  tasks:
  - name: Get EC2 Instance Facts
    ec2_instance_info:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      region: "{{ ec2_region }}"
      filters:
        tag:AlwaysUp: "False"
    register: ec2_result

  - name: dump ec2_result
    debug:
      var: ec2_result
    when: debug_flag is defined

  - name: Destroy instances
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      region: "{{ ec2_region }}"
      wait: false
      instance_ids: "{{ item.instance_id }}"
      state: absent
      instance_initiated_shutdown_behavior: terminate
    with_items: "{{ ec2_result.instances }}"

 
