---
- name: Manage Untagged Instances
  hosts: all
  gather_facts: false

  vars_files:
  - group_vars/na-west

  tasks:
    - name: Loop through each region
      include_role:
        name: manage-untagged-instances
      vars:
        aws_region: "{{ aws_region_var }}"
      loop: "{{ aws_regions }}"
      loop_control:
        loop_var: aws_region_var
